TCMI.Admin/TCMI.Admin/Controllers/PrayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCMI.Admin.TCMIContentServices;
using TCMI.Admin.Models;

namespace TCMI.Admin.Controllers
{
    [Authorize] 
    public class PrayerController : Controller
    {
        //
        // GET: /Prayer/
        public TCMIContentServices.TCMIContentSoapClient client = new TCMIContentSoapClient();
               
        public ActionResult Index()
        {
            IEnumerable<TCMI.Admin.TCMIContentServices.Prayer> result = client.GetPrayers().ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ActionName("Create")]
        public ActionResult CreatePost(PrayerMeta prayer)
        {
            string retValue = string.Empty;
            if (ModelState.IsValid)
            {
                TCMIContentServices.TCMIContentSoapClient client = new TCMIContentSoapClient();
                retValue = client.AddPrayer(prayer.Name, prayer.Email, prayer.Phone, prayer.Confidentiality, prayer.PrayerRequest);
                ViewBag.ReturnMessage = retValue;
                return RedirectToAction("index");
            }
            ViewBag.ReturnMessage = retValue;
            return View();
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            TCMI.Admin.TCMIContentServices.Prayer p = client.GetPrayers().FirstOrDefault(prayer => prayer.id.Equals(id));
            PrayerMeta _p = new PrayerMeta
            {
                id = p.id,
                Name = p.Name,
                Email = p.Email,
                Phone = p.Phone,
                Confidentiality = p.Confidentiality,
                PrayerRequest = p.PrayerRequest,
                Prayed = p.Prayed,
                Answered = p.Answered,
                Received = p.Received
            };
            return View(_p);
        }

        [HttpPost]
        public ActionResult Update(PrayerMeta p)
        {
            if (ModelState.IsValid)
            {
                client.UpdatePrayer(p.id, p.Name, p.Email, p.Phone, p.Confidentiality, p.PrayerRequest, p.Prayed,p.Answered.Value);
                return RedirectToAction("index");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            TCMI.Admin.TCMIContentServices.Prayer p = client.GetPrayers().FirstOrDefault(prayer => prayer.id.Equals(id));
            PrayerMeta _p = new PrayerMeta
            {
                id = p.id,
                Name = p.Name,
                Email = p.Email,
                Phone = p.Phone,
                Confidentiality = p.Confidentiality,
                PrayerRequest = p.PrayerRequest,
                Prayed = p.Prayed,
                Answered = p.Answered,
                Received = p.Received
            };
            return View(_p);
        }


        [HttpGet]
        public ActionResult Remove(int id)
        {
            TCMI.Admin.TCMIContentServices.Prayer p = client.GetPrayers().FirstOrDefault(prayer => prayer.id.Equals(id));
            PrayerMeta _p = new PrayerMeta
            {
                id = p.id,
                Name = p.Name,
                Email = p.Email,
                Phone = p.Phone,
                Confidentiality = p.Confidentiality,
                PrayerRequest = p.PrayerRequest,
                Prayed = p.Prayed,
                Answered = p.Answered,
                Received = p.Received
            };
            return View(_p);
        }

        [HttpPost]
        [ActionName("Remove")]
        public ActionResult RemovePost(int id)
        {
            if (ModelState.IsValid)
            {
                client.RemovePrayer(id);
                return RedirectToAction("index");
            }

            return View();
        }
    }
}

TCMI.Admin/TCMI.Admin/Views/Prayer/Create.cshtml
@model TCMI.Admin.Models.PrayerMeta

@{
    ViewBag.Title = "Create";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/InsertUpdate.js"></script>

<link href="~/Content/default.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<header>
    <img src="~/Images/logo.png" />
    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("index","home")" class="navbar-brand">TCMI Admin</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ><a href="@Url.Action("index","event")">Events</a></li>
                <li class="active"><a href="@Url.Action("index","prayer")">Prayer</a></li>
                @*<li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="#">Inbox</a></li>
                            <li><a href="#">Drafts</a></li>
                            <li><a href="#">Sent Items</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Trash</a></li>
                        </ul>
                    </li>*@
            </ul>
            @*<form role="search" class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" placeholder="Search" class="form-control">
                </div>
            </form>*@
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("logout","user")">Log Out</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="page-header"><h2>Create</h2></div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="panel panel-primary">
            <div class="panel-heading">Create</div>

            <div class="panel-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name)

                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email)

                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone)

                    @Html.EditorFor(model => model.Phone)
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Confidentiality)

                    @Html.DropDownListFor(model => model.Confidentiality, new List<SelectListItem> {
                                                                new SelectListItem { Value="Public",Text="Public"},
                                                                new SelectListItem{ Value="Anonymous",Text="Anonymous"},
                                                                new SelectListItem{ Value="Private",Text="Private"}
                                                                  }, "Select Confidentiality")
                    @Html.ValidationMessageFor(model => model.Confidentiality)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrayerRequest)

                    @Html.TextAreaFor(model => model.PrayerRequest)
                    @Html.ValidationMessageFor(model => model.PrayerRequest)
                </div>
            </div>
            <div class="panel-footer">
                <p>
                    <button type="submit" class="btn btn-default" ><i class="fa fa-floppy-o" ></i> Save</button>
                </p>
            </div>
        </div> <!--end panel-->

    }


    <div>
        <a href="@Url.Action("index", "prayer")"  ><i class='fa fa-chevron-left'></i> Back to List</a>
        @*@Html.ActionLink("Back to List", "Index")*@
    </div>
</div>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

TCMI.Admin/TCMI.Admin/Views/Prayer/Details.cshtml
@model TCMI.Admin.Models.PrayerMeta

@{
    ViewBag.Title = "Details";
}


<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/default.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<header>
    <img src="~/Images/logo.png" />
    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("index","home")" class="navbar-brand">TCMI Admin</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ><a href="@Url.Action("index","event")">Events</a></li>
                <li class="active"><a href="@Url.Action("index","prayer")">Prayer</a></li>
                @*<li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="#">Inbox</a></li>
                            <li><a href="#">Drafts</a></li>
                            <li><a href="#">Sent Items</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Trash</a></li>
                        </ul>
                    </li>*@
            </ul>
            @*<form role="search" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" placeholder="Search" class="form-control">
                    </div>
                </form>*@
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("logout","user")">Log Out</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="page-header"><h2>Details</h2></div>



    <div class="panel panel-primary">
        <div class="panel-heading">Details</div>

        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(model => model.Name)

                @Html.EditorFor(model => model.Name)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email)

                @Html.EditorFor(model => model.Email)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone)

                @Html.EditorFor(model => model.Phone)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Confidentiality)

                @Html.DropDownListFor(model => model.Confidentiality, new List<SelectListItem> {
                                                                new SelectListItem { Value="Public",Text="Public"},
                                                                new SelectListItem{ Value="Anonymous",Text="Anonymous"},
                                                                new SelectListItem{ Value="Private",Text="Private"}
                                                                  }, "Select Confidentiality")

            </div>

            <div class="form-group">
                <label>Prayer Request</label>

                @Html.TextAreaFor(model => model.PrayerRequest)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Received)

                @Html.EditorFor(model => model.Received)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Answered)

                @Html.EditorFor(model => model.Answered)

            </div>
        </div>
        <div class="panel-footer">
            <a href="@Url.Action("index", "prayer")"><i class='fa fa-chevron-left'></i> Back to List</a> |
            <a href="@Url.Action("update", "prayer", new { id = Model.id })"><i class='fa fa fa-pencil'></i> Update</a>
            
            @*@Html.ActionLink("Update", "Update", new { id = Model.id }) |
            @Html.ActionLink("Back to List", "Index")*@
        </div>
    </div> <!--end panel-->
</div>

<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("form-control").attr("disabled", true);
        $("input[type=email]").addClass("form-control").attr("disabled", true);
        $("input[type=datetime]").addClass("form-control").attr("disabled", true);
        $("textarea").addClass("form-control").attr("disabled", true);
        $("select").addClass("form-control").attr("disabled", true);
    });
</script>

TCMI.Admin/TCMI.Admin/Views/Prayer/Index.cshtml
@model IEnumerable<TCMI.Admin.TCMIContentServices.Prayer>

@{
    ViewBag.Title = "Prayer Request";
}



<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<link href="~/Content/default.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<header>
    <img src="~/Images/logo.png" />
    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("index","home")" class="navbar-brand">TCMI Admin</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ><a href="@Url.Action("index","event")">Events</a></li>
                <li class="active"><a href="@Url.Action("index","prayer")">Prayer</a></li>
                @*<li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="#">Inbox</a></li>
                            <li><a href="#">Drafts</a></li>
                            <li><a href="#">Sent Items</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Trash</a></li>
                        </ul>
                    </li>*@
            </ul>
            <form role="search" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" placeholder="Search" class="form-control">
                    </div>
                </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("logout","user")">Log Out</a></li>
            </ul>
        </div>
    </nav>
</header><div class="container">
    <div class="page-header">
        <h2>Prayer Request</h2>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Prayer Request
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Phone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Confidentiality)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Received)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Prayed)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Answered)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Phone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Confidentiality)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Received)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Prayed)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Answered)
                            </td>
                            <td>
                                <a href="@Url.Action("Update", "Prayer", new { id = item.id })" class="btn btn-primary btn-index" title="Update"><i class='fa fa-pencil'></i></a>
                                <a href="@Url.Action("Details", "Prayer", new { id = item.id })" class="btn btn-primary btn-index" title="Details"><i class='fa fa-file-text'></i></a>
                                <a href="@Url.Action("Remove", "Prayer", new { id = item.id })" class="btn btn-danger btn-index" title="Remove"><i class='fa fa-trash'></i></a>
                                @*@Html.ActionLink("Update", "Update", new { id = item.id }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                                    @Html.ActionLink("Remove", "Remove", new { id = item.id })*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <p>

                <a href="@Url.Action("Create", "Prayer")" class="btn btn-primary" title="New Record"><i class='fa fa-plus-square'></i></a>
                @*@Html.ActionLink("Create New", "Create")*@
            </p>
        </div>
    </div>





</div>

TCMI.Admin/TCMI.Admin/Views/Prayer/Remove.cshtml
@model TCMI.Admin.Models.PrayerMeta

@{
    ViewBag.Title = "Remove";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<link href="~/Content/default.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<header>
    <img src="~/Images/logo.png" />
    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("index","home")" class="navbar-brand">TCMI Admin</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ><a href="@Url.Action("index","event")">Events</a></li>
                <li class="active"><a href="@Url.Action("index","prayer")">Prayer</a></li>
                @*<li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="#">Inbox</a></li>
                            <li><a href="#">Drafts</a></li>
                            <li><a href="#">Sent Items</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Trash</a></li>
                        </ul>
                    </li>*@
            </ul>
            @*<form role="search" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" placeholder="Search" class="form-control">
                    </div>
                </form>*@
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("logout","user")">Log Out</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="page-header"><h2>Remove Prayer Request</h2><h3>Are you sure you want to delete this?</h3></div>
    <div class="panel panel-primary">
        <div class="panel-heading">Remove</div>

        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(model => model.Name)

                @Html.EditorFor(model => model.Name)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email)

                @Html.EditorFor(model => model.Email)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone)

                @Html.EditorFor(model => model.Phone)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Confidentiality)

                @Html.DropDownListFor(model => model.Confidentiality, new List<SelectListItem> {
                                                                new SelectListItem { Value="Public",Text="Public"},
                                                                new SelectListItem{ Value="Anonymous",Text="Anonymous"},
                                                                new SelectListItem{ Value="Private",Text="Private"}
                                                                  }, "Select Confidentiality")

            </div>

            <div class="form-group">
                <label>Prayer Request</label>

                @Html.TextAreaFor(model => model.PrayerRequest)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Received)

                @Html.EditorFor(model => model.Received)

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Answered)

                @Html.EditorFor(model => model.Answered)

            </div>
        </div>
        <div class="panel-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <p>
                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                </p>
            }
        </div>
    </div> <!--end panel-->
    <a href="@Url.Action("index", "prayer")"><i class='fa fa-chevron-left'></i> Back to List</a>

</div>

<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("form-control").attr("disabled", true);
        $("input[type=email]").addClass("form-control").attr("disabled", true);
        $("input[type=datetime]").addClass("form-control").attr("disabled", true);
        $("textarea").addClass("form-control").attr("disabled", true);
        $("select").addClass("form-control").attr("disabled", true);
    });
</script>

TCMI.Admin/TCMI.Admin/Views/Prayer/Update.cshtml
@model TCMI.Admin.Models.PrayerMeta

@{
    ViewBag.Title = "Update";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/default.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/InsertUpdate.js"></script>

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<header>
    <img src="~/Images/logo.png" />
    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("index","home")" class="navbar-brand">TCMI Admin</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ><a href="@Url.Action("index","event")">Events</a></li>
                <li class="active"><a href="@Url.Action("index","prayer")">Prayer</a></li>
                @*<li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="#">Inbox</a></li>
                            <li><a href="#">Drafts</a></li>
                            <li><a href="#">Sent Items</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Trash</a></li>
                        </ul>
                    </li>*@
            </ul>
            @*<form role="search" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" placeholder="Search" class="form-control">
                    </div>
                </form>*@
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("logout","user")">Log Out</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="page-header"><h2>Update</h2></div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="panel panel-primary">
            <div class="panel-heading">Update</div>

            <div class="panel-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name)

                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email)

                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone)

                    @Html.EditorFor(model => model.Phone)
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Confidentiality)

                    @Html.DropDownListFor(model => model.Confidentiality, new List<SelectListItem> {
                                                                new SelectListItem { Value="Public",Text="Public"},
                                                                new SelectListItem{ Value="Anonymous",Text="Anonymous"},
                                                                new SelectListItem{ Value="Private",Text="Private"}
                                                                  }, "Select Confidentiality")
                    @Html.ValidationMessageFor(model => model.Confidentiality)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrayerRequest)

                    @Html.TextAreaFor(model => model.PrayerRequest)
                    @Html.ValidationMessageFor(model => model.PrayerRequest)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Answered)

                    @Html.EditorFor(model => model.Answered)
                    @Html.ValidationMessageFor(model => model.Answered)

                </div>
            </div>
            <div class="panel-footer">
                <p>
                    <button type="submit" class="btn btn-default"><i class="fa fa-floppy-o"></i> Save</button>
                </p>
            </div>
        </div> <!--end panel-->

    }


    <div>
        <a href="@Url.Action("index", "prayer")"><i class='fa fa-chevron-left'></i> Back to List</a>
    </div>
</div>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@